project:
  type: website
  output-dir: docs
  
website:
  title: " "
  navbar:
    left:
      - href: index.qmd
        text: Ysela Ochoa Tapia
      - href: projects.qmd
        text: Clases
      - href: talks.qmd
        text: Presentaciones
      - href: about.qmd
        text: Acerca de Mi
    tools:
      - icon: github
        href: https://github.com/yselaot
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Ysela Ochoa Tapia"
  reader-mode: true
format:
  html:
    theme: 
      light: quartz
      dark: darkly
    toc: true

editor: source

